import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraWrapper, ContextWrapper } from "@/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ChakraWrapper>
        <ContextWrapper>
          <body className={inter.className}>{children}</body>
        </ContextWrapper>
      </ChakraWrapper>
    </html>
  );
}
